services:
  aikidatabuilder:
    image: aikidatabuilder
    build:
      context: .
      dockerfile: AikiDataBuilder/Dockerfile
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
      

  asadiscordbot:
    image: asadiscordbot
    build:
      context: .
      dockerfile: ASADiscordBot/Dockerfile

  asadiscordbot:
    image: asadiscordbot
    build:
      context: .
      dockerfile: ASADiscordBot/Dockerfile
