services:
  aikidatabuilder:
    image: aikidatabuilder
    build:
      context: .
      dockerfile: AikiDataBuilder/Dockerfile
    environment:
      - DOTNET_RUNNING_IN_DOCKER=true
      - DEFAULT_CONNECTION_DOCKER=Server=mssql,1433;Database=my_database;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - mssql
    env_file:
      - .env

  asadiscordbot:
    image: asadiscordbot
    build:
      context: .
      dockerfile: ASADiscordBot/Dockerfile
    environment:
      - DOTNET_RUNNING_IN_DOCKER=true
      - DEFAULT_CONNECTION_DOCKER=Server=mssql,1433;Database=asa_database;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - mssql
    env_file:
      - .env
        
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  
volumes:
  mssql-data: