services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    
  deep_seek:
    build:
      context: ./DeepSeek
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_OFFLINE=0
      - OMP_NUM_THREADS=6
      - MKL_NUM_THREADS=6
      - MALLOC_TRIM_THRESHOLD_=0
      - TOKENIZERS_PARALLELISM=true
    volumes:
      - ./model_cache:/root/.cache/huggingface  # Cache the model
    command: uvicorn deepseek_api:app --host 0.0.0.0 --port 8000 --log-level info --timeout-keep-alive 120
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '7'
        reservations:
          cpus: '6'
networks:
  my_network:
    driver: bridge